export const proposalsConstants = {
  GETRFPPROPOSAL_REQUEST: "GETRFPPROPOSAL_REQUEST",
  GETRFPPROPOSAL_SUCCESS: "GETRFPPROPOSAL_SUCCESS",
  GETRFPPROPOSAL_FAILURE: "GETRFPPROPOSAL_FAILURE",

  GETRFPPROPOSALPAGES_REQUEST: "GETRFPPROPOSALPAGES_REQUEST",
  GETRFPPROPOSALPAGES_SUCCESS: "GETRFPPROPOSALPAGES_SUCCESS",
  GETRFPPROPOSALPAGES_FAILURE: "GETRFPPROPOSALPAGES_FAILURE",

  GETRFPPROPOSALBYDOMAIN_REQUEST: "GETRFPPROPOSALBYDOMAIN_REQUEST",
  GETRFPPROPOSALBYDOMAIN_SUCCESS: "GETRFPPROPOSALBYDOMAIN_SUCCESS",
  GETRFPPROPOSALBYDOMAIN_FAILURE: "GETRFPPROPOSALBYDOMAIN_FAILURE",

  GETRFPBYDOMAIN_REQUEST: "GETRFPBYDOMAIN_REQUEST",
  GETRFPBYDOMAIN_SUCCESS: "GETRFPBYDOMAIN_SUCCESS",
  GETRFPBYDOMAIN_FAILURE: "GETRFPBYDOMAIN_FAILURE",

  GETRFPBYSTATUS_REQUEST: "GETRFPBYSTATUS_REQUEST",
  GETRFPBYSTATUS_SUCCESS: "GETRFPBYSTATUS_SUCCESS",
  GETRFPBYSTATUS_FAILURE: "GETRFPBYSTATUS_FAILURE",

  GETRFPBYTYPE_REQUEST: "GETRFPBYTYPE_REQUEST",
  GETRFPBYTYPE_SUCCESS: "GETRFPBYTYPE_SUCCESS",
  GETRFPBYTYPE_FAILURE: "GETRFPBYTYPE_FAILURE",

  GETRFPBYCONTRACT_REQUEST: "GETRFPBYCONTRACT_REQUEST",
  GETRFPBYCONTRACT_SUCCESS: "GETRFPBYCONTRACT_SUCCESS",
  GETRFPBYCONTRACT_FAILURE: "GETRFPBYCONTRACT_FAILURE",

  GETRFPBYACTION_REQUEST: "GETRFPBYACTION_REQUEST",
  GETRFPBYACTION_SUCCESS: "GETRFPBYACTION_SUCCESS",
  GETRFPBYACTION_FAILURE: "GETRFPBYACTION_FAILURE",

  GETRFPBYSUBMISSION_REQUEST: "GETRFPBYSUBMISSION_REQUEST",
  GETRFPBYSUBMISSION_SUCCESS: "GETRFPBYSUBMISSION_SUCCESS",
  GETRFPBYSUBMISSION_FAILURE: "GETRFPBYSUBMISSION_FAILURE",

  GETRFPBYSOURCE_REQUEST: "GETRFPBYSOURCE_REQUEST",
  GETRFPBYSOURCE_SUCCESS: "GETRFPBYSOURCE_SUCCESS",
  GETRFPBYSOURCE_FAILURE: "GETRFPBYSOURCE_FAILURE",

  GETRFPBYOWNER_REQUEST: "GETRFPBYOWNER_REQUEST",
  GETRFPBYOWNER_SUCCESS: "GETRFPBYOWNER_SUCCESS",
  GETRFPBYOWNER_FAILURE: "GETRFPBYOWNER_FAILURE",

  GETRFPBYCOUNTRY_REQUEST: "GETRFPBYCOUNTRY_REQUEST",
  GETRFPBYCOUNTRY_SUCCESS: "GETRFPBYCOUNTRY_SUCCESS",
  GETRFPBYCOUNTRY_FAILURE: "GETRFPBYCOUNTRY_FAILURE",
};
