export const userConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',

    UPDATEPASSOWRD_REQUEST : 'UPDATEPASSOWRD_REQUEST',
    UPDATEPASSOWRD_SUCCESS : 'UPDATEPASSOWRD_SUCCESS',
    UPDATEPASSOWRD_FAILURE : 'UPDATEPASSOWRD_FAILURE',

    RESETUSERPASSOWRD_REQUEST : 'RESETUSERPASSOWRD_REQUEST',
    RESETUSERPASSOWRD_SUCCESS : 'RESETUSERPASSOWRD_SUCCESS',
    RESETUSERPASSOWRD_FAILURE : 'RESETUSERPASSOWRD_FAILURE',

    VERYFYTEMPPWD_REQUEST: 'VERYFYTEMPPWD_REQUEST',
    VERYFYTEMPPWD_SUCCESS: 'VERYFYTEMPPWD_SUCCESS',
    VERYFYTEMPPWD_FAILURE: 'VERYFYTEMPPWD_FAILURE',

};
